name: cesizen-api

services:
  app:
    build:
      context: ./cesizen-app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./cesizen-app:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    restart: unless-stopped

  # Lance le conteneur d'API Symfony
  api:
    build:
      context: ./cesizen-api
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
      mailpit:
        condition: service_started
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      APP_SECRET: change-me-in-docker
      DATABASE_URL: mysql://cesizen:cesizen@database:3306/cesizen?serverVersion=mariadb-11.4.2&charset=utf8mb4
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: cesizen
      DB_USER: cesizen
      DB_PASSWORD: cesizen
      JWT_SECRET: docker-jwt-secret
      JWT_TTL: 3600
      REFRESH_TOKEN_TTL: 2592000
      MAILER_FROM_EMAIL: no-reply@cesizen.local
      SMTP_HOST: mailpit
      SMTP_PORT: 1025
    ports:
      - "8000:80"
    restart: unless-stopped

  # Lance le conteneur de base de données MariaDB
  database:
    image: mariadb:11.4
    environment:
      MARIADB_DATABASE: cesizen
      MARIADB_USER: cesizen
      MARIADB_PASSWORD: cesizen
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    restart: unless-stopped

  # Lance le conteneur de phpMyAdmin après la BDD MariaDB pour gérer la base de données à partir d'une interface web (pas besoin de software extérieur)
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: database
      PMA_USER: cesizen
      PMA_PASSWORD: cesizen
    ports:
      - "8080:80"
    depends_on:
      - database
    restart: unless-stopped

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"
    restart: unless-stopped

volumes:
  mariadb_data:
