name: cesizen-api

services:
  app:
    image: ghcr.io/loic-1/cesizen-api-app:dev
    ports:
      - "5173:5173"
    volumes:
      - ./cesizen-app:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    restart: unless-stopped

  # Lance le conteneur d'API Symfony
  api:
    image: ghcr.io/loic-1/cesizen-api-api:dev
    depends_on:
      database:
        condition: service_healthy
      mailpit:
        condition: service_started
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_TTL: ${JWT_TTL}
      REFRESH_TOKEN_TTL: ${REFRESH_TOKEN_TTL}
      MAILER_FROM_EMAIL: ${MAILER_FROM_EMAIL}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
    ports:
      - "8000:80"
    restart: unless-stopped

  # Lance le conteneur de base de données MariaDB
  database:
    image: mariadb:11.4
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    restart: unless-stopped

  # Lance le conteneur de phpMyAdmin après la BDD MariaDB pour gérer la base de données à partir d'une interface web (pas besoin de software extérieur)
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - database
    restart: unless-stopped

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"
    restart: unless-stopped

volumes:
  mariadb_data:
