api_platform:
    title: Bookshop API
    version: 1.0.0
    enable_docs: false
    enable_swagger: false
    enable_swagger_ui: false
    enable_re_doc: false
    formats:
        json:
            mime_types:
                - application/json
    error_formats:
        json:
            - application/json
    patch_formats:
        json:
            mime_types:
                - application/merge-patch+json
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    swagger:
        api_keys:
            bearerAuth:
                name: Authorization
                type: header
